// todo-vue/src/components/TodoForm.vue
<template>
    <form v-on:submit.prevent="addTodo(newTodo)" class="form-inline">
        <input type="text"
               v-model="newTodo.title"
               class="form-control"
               placeholder="add a new todo...">
        <button type="submit" class="btn btn-default">Add</button>
    </form>
</template>
<style>
    .form-inline .form-control {
        width: 50%;
    }
</style>
<script>
export default {
    props: ['todos'],
    data() {
        return {
            newTodo: { id: null, title: '', completed: false },
        };
    },
    methods: {
        addTodo(newTodo) {
            this.todos.push(newTodo);
            this.newTodo = { id: null, title: '', completed: false };
        },
    },
};
</script>

// todo-react/src/components/TodoForm/TodoForm.js
import React, { Component } from 'react';
import './TodoForm.css';

class TodoForm extends Component {
    constructor(props) {
        super(props);
        this.onSubmit = this.onSubmit.bind(this);
    }
    componentDidMount() {
        this.refs.itemName.focus();
    }
    onSubmit(event) {
        event.preventDefault();
        var newItemValue = this.refs.itemName.value;
        
        if(newItemValue) {
        this.props.addItem({newItemValue});
        this.refs.form.reset();
        }
    }
    render () {
        return (
        <form ref="form" onSubmit={this.onSubmit} className="form-inline">
            <input type="text" ref="itemName" className="form-control" placeholder="add a new todo..."/>
            <button type="submit" className="btn btn-default">Add</button> 
        </form>
        );   
    }
}

export default TodoForm
